[package]
name = "prust"
version = "0.1.0"
authors = ["Selman Özleyen <32667648+SelmanOzleyen@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.6.0"