[package]
name = "spp"
version = "0.1.0"
authors = ["SelmanOzleyen <selman.ozleyen2017@gtu.edu.tr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
